#!/bin/bash

set -e
shopt -s extglob

OUTDIR="${BUILT_PRODUCTS_DIR}/${TARGET_NAME}"
if [ "${ACTION}" == "clean" ]; then
	echo Remove "${OUTDIR}"
	if [ -n "${OUTDIR}" ]; then
		rm -rf "${OUTDIR}"
		for ARCH in $ARCHS; do
			rm -rf "${OUTDIR}/${ARCH}"
		done
	fi
else
	# For yasm and gas
	PATH=$PATH:${SRCROOT}/gas:/opt/homebrew/bin:/usr/local/bin

	echo Build in ${OUTDIR}
	BUILT=""
	for ARCH in $ARCHS; do
		mkdir -p "${OUTDIR}/${ARCH}"
		cd "${OUTDIR}/${ARCH}"
		if [ -f config.h ]; then
			echo Skipping configure
		else
			if [ "${CONFIGURATION}" == "Debug" ]; then
				FLAGS="--disable-optimizations"
			else
				FLAGS=
			fi
			if [ $ARCH == arm64 ]; then
				FLAGS="$FLAGS --enable-cross-compile --enable-vfp --enable-neon"
			elif [ $ARCH == x86_64 ]; then
				FLAGS="$FLAGS --enable-cross-compile --cpu=haswell"
			fi
			PKG_CONFIG_LIBDIR="${BUILT_PRODUCTS_DIR}/${ARCH}/lib/pkgconfig" "${SRCROOT}/${TARGET_NAME}/configure" --prefix="${BUILT_PRODUCTS_DIR}/${ARCH}" --arch=${ARCH} --cc="clang -arch ${ARCH}" ${FLAGS} --extra-ldexeflags=-liconv --disable-stripping --enable-gpl --enable-hardcoded-tables --disable-doc --disable-indevs --disable-outdevs --disable-network --disable-avdevice --disable-muxers --disable-encoders --disable-bsfs --disable-filters --disable-protocols --disable-autodetect --enable-appkit --enable-avfoundation --enable-bzlib --enable-coreimage --enable-iconv --enable-libaom --enable-zlib --enable-audiotoolbox --enable-videotoolbox --enable-muxer=image2 --enable-encoder=png --enable-protocol=file --enable-protocol=pipe
		fi
		make -j`sysctl -n hw.physicalcpu` install
	done

	# Combine into Universal
	mkdir -p "${BUILT_PRODUCTS_DIR}/universal/include"
	# Assumes there aren't any material client impacting differences in config between archs
	cp -p "${OUTDIR}/${ARCHS/ */}/config.h" "${BUILT_PRODUCTS_DIR}/universal/include/"

	mkdir -p "${BUILT_PRODUCTS_DIR}/universal/lib"
	for LIB in libavcodec libavfilter libavformat libavutil libpostproc libswresample libswscale; do
		cp -pr "${BUILT_PRODUCTS_DIR}/${ARCHS/ */}/include/${LIB}" "${BUILT_PRODUCTS_DIR}/universal/include/"
		lipo -create "${BUILT_PRODUCTS_DIR}/"+(${ARCHS/ /|})"/lib/${LIB}.a" -output "${BUILT_PRODUCTS_DIR}/universal/lib/${LIB}.a"
	done
fi
