#!/bin/bash

OUTDIR="${TARGET_BUILD_DIR}/${TARGET_NAME}"
if [ "${ACTION}" == "clean" ]; then
	echo Remove "${OUTDIR}"
	if [ -n "${OUTDIR}" ]; then
		rm -rf "${OUTDIR}"
	fi
else
	# For yasm
	PATH=$PATH:/usr/local/bin

	if [ ! -x "${SRCROOT}/${TARGET_NAME}/configure" ]; then
		echo Clone to ${SRCROOT}/${TARGET_NAME}
		cd "${SRCROOT}"
		git submodule update --init
	fi
	echo Build in ${OUTDIR}
	mkdir -p "${OUTDIR}"
	cd "${OUTDIR}"
	if [ -f config.h ]; then
		echo Skipping configure
	else
		if [ "${CONFIGURATION}" == "Debug" ]; then
			FLAGS="--disable-optimizations"
		else
			FLAGS=
		fi
		"${SRCROOT}/${TARGET_NAME}/configure" --cc=clang --arch=x86_64 --cpu=core2 --extra-cflags=-I${SRCROOT}/aom --extra-ldexeflags="-liconv -L${TARGET_BUILD_DIR}/aom" --disable-stripping --enable-gpl --enable-hardcoded-tables --disable-doc --disable-pthreads --disable-indevs --disable-outdevs --disable-network --disable-avdevice --disable-muxers --disable-encoders --disable-bsfs --disable-filters --disable-protocols --disable-autodetect --enable-appkit --enable-avfoundation --enable-bzlib --enable-coreimage --enable-iconv --enable-libaom --enable-zlib --enable-audiotoolbox --enable-videotoolbox --enable-muxer=image2 --enable-encoder=png --enable-protocol=file ${FLAGS}
	fi
	make -j`sysctl -n hw.physicalcpu` ${ACTION}
fi
