#!/bin/bash

set -e
shopt -s extglob

SCRIPT=`readlink -fn "$0"`

if [ "${ACTION}" == "clean" ]; then
	echo Remove "${OBJECT_FILE_DIR}"
	[ -n "${OBJECT_FILE_DIR}" -a -d "${OBJECT_FILE_DIR}" ] && rm -rf "${OBJECT_FILE_DIR}"
else
	# For automake and pkg-config
	PATH=$PATH:/opt/homebrew/bin:/usr/local/bin

	echo Build in ${OBJECT_FILE_DIR}
	BUILT=""
	for ARCH in $ARCHS; do
		mkdir -p "${OBJECT_FILE_DIR}/${ARCH}"
		cd "${SRCROOT}/${TARGET_NAME}"
		if [ -f configure -a configure -nt "${SCRIPT}" ]; then
			echo Skipping autoreconf
		else
			./autogen.sh
		fi
		cd "${OBJECT_FILE_DIR}/${ARCH}"
		if [ -f config.status -a config.status -nt "${SCRIPT}" ]; then
			echo Skipping configure
		else
			rm -f config.status
			if [ "${CONFIGURATION}" == "Debug" ]; then
				FLAGS="--enable-debug"
			fi
			PKG_CONFIG_LIBDIR="${BUILT_PRODUCTS_DIR}/${ARCH}/lib/pkgconfig" CPPFLAGS="-arch ${ARCH} -fapplication-extension" LDFLAGS="-arch ${ARCH}" "${SRCROOT}/${TARGET_NAME}/configure" --host=${ARCH}-apple-darwin${MACOSX_DEPLOYMENT_TARGET} --prefix="${BUILT_PRODUCTS_DIR}/${ARCH}" ${FLAGS}
		fi
		make -j`sysctl -n hw.physicalcpu` install

		# Fix up install name
		DYLIB=$(basename `otool -DX ${BUILT_PRODUCTS_DIR}/${ARCH}/lib/libzimg.dylib`)
		install_name_tool -id @rpath/${DYLIB} ${BUILT_PRODUCTS_DIR}/${ARCH}/lib/libzimg.dylib
	done

	# Combine into Universal
	echo Installing into ${BUILT_PRODUCTS_DIR}/universal
	mkdir -p "${BUILT_PRODUCTS_DIR}/universal/include"
	cp -p "${BUILT_PRODUCTS_DIR}/${ARCHS/ */}/include/zimg.h" "${BUILT_PRODUCTS_DIR}/universal/include/"

	mkdir -p "${CONFIGURATION_BUILD_DIR}/universal/lib/pkgconfig"
	cp -p "${BUILT_PRODUCTS_DIR}/${ARCHS/ */}/lib/pkgconfig/zimg.pc" "${BUILT_PRODUCTS_DIR}/universal/lib/pkgconfig/"

	lipo -create "${BUILT_PRODUCTS_DIR}/"+(${ARCHS/ /|})"/lib/libzimg.a" -output "${BUILT_PRODUCTS_DIR}/universal/lib/libzimg.a"
	# Install using the dylib's "install name" since that's what other FFmpeg dylibs will look for
	DYLIB=$(basename `otool -DX ${BUILT_PRODUCTS_DIR}/${ARCHS/ */}/lib/libzimg.dylib`)
	lipo -create "${BUILT_PRODUCTS_DIR}/"+(${ARCHS/ /|})"/lib/libzimg.dylib" -output "${BUILT_PRODUCTS_DIR}/universal/lib/${DYLIB}"
fi
